#PBS -N gzy_ex4_trap_4
#PBS -l nodes=16:ppn=32
#PBS -j oe

echo "This is gzy's lab"$PBS_JOBID@PBS_QUEUE
cd $PBS_O_WORKDIR
source /public/software/profile.d/mpi_openmpi-intel-2.1.2.sh
mpiexec -np 1 ./trap-4 0 4 1 2 1024
mpiexec -np 2 ./trap-4 0 4 1 2 1024
mpiexec -np 4 ./trap-4 0 4 1 2 1024
mpiexec -np 8 ./trap-4 0 4 1 2 1024
mpiexec -np 16 ./trap-4 0 4 1 2 1024
mpiexec -np 32 ./trap-4 0 4 1 2 1024
mpiexec -np 64 ./trap-4 0 4 1 2 1024
mpiexec -np 128 ./trap-4 0 4 1 2 1024
mpiexec -np 256 ./trap-4 0 4 1 2 1024
mpiexec -np 512 ./trap-4 0 4 1 2 1024

